import { pgTable, text, jsonb } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  uid: text("uid"),
  name: text("name").notNull(),
  email: text("email").notNull(),
  password: text("password"),
  role: text("role").notNull(),
  leadData: jsonb("lead_data"),
});

export const estimates = pgTable("estimates", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  name: text("name").notNull(),
  date: text("date").notNull(),
  selections: jsonb("selections"),
  totalCost: text("total_cost"),
  notes: text("notes"),
  selectedServices: jsonb("selected_services"),
});

export const leads = pgTable("leads", {
  id: text("id").primaryKey(),
  homeowner: text("homeowner").notNull(),
  phone: text("phone"),
  email: text("email"),
  address: text("address"),
  leadSource: text("lead_source"),
  renovationInterest: text("renovation_interest"),
  assignedSalesperson: text("assigned_salesperson"),
  lastContact: text("last_contact"),
  nextFollowUp: text("next_follow_up"),
  estimatedValue: text("estimated_value"),
  probability: text("probability"),
  expectedCloseDate: text("expected_close_date"),
  stage: text("stage"),
});

export const projects = pgTable("projects", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  homeowner: text("homeowner"),
  address: text("address"),
  phone: text("phone"),
  email: text("email"),
  preferredContact: text("preferred_contact"),
  emergencyContact: text("emergency_contact"),
  renovationType: text("renovation_type"),
  stage: text("stage"),
  status: text("status"),
  progress: text("progress"),
  contractValue: text("contract_value"),
  budget: text("budget"),
  startDate: text("start_date"),
  estimatedCompletion: text("estimated_completion"),
  accountManager: text("account_manager"),
  projectManager: text("project_manager"),
  superintendent: text("superintendent"),
  crew: jsonb("crew"),
  subcontractors: jsonb("subcontractors"),
  scopeOfWork: text("scope_of_work"),
  roomsIncluded: jsonb("rooms_included"),
  permitStatus: text("permit_status"),
  materialSelections: jsonb("material_selections"),
  changeOrders: jsonb("change_orders"),
  milestones: jsonb("milestones"),
  amNotes: jsonb("am_notes"),
  pmNotes: jsonb("pm_notes"),
  contracts: jsonb("contracts"),
  payments: jsonb("payments"),
  warranty: jsonb("warranty"),
  documents: jsonb("documents"),
  activityFeed: jsonb("activity_feed"),
});

export const events = pgTable("events", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  date: text("date").notNull(),
  time: text("time"),
  assignedEmployee: text("assigned_employee"),
  homeowner: text("homeowner"),
  location: text("location"),
  notes: text("notes"),
  status: text("status"),
  type: text("type"),
});
